name: Build and Push Docker Image

on:
  push:
    branches:
      - main

  release:
    types:
      - published
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3


      # Generate the version tag
      - name: Determine next version
        id: version
        run: |
          # Get the latest tag in the repository
          TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "Latest tag: $TAG"

          # Bump the patch version
          IFS='.' read -r MAJOR MINOR PATCH <<< "${TAG#v}"
          PATCH=$((PATCH+1))
          NEXT_VERSION="v$MAJOR.$MINOR.$PATCH"

          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV
          echo "::set-output name=version::$NEXT_VERSION"
 
 
      # Create a new Git tag
      - name: Create new Git tag
        run: |
          git tag ${{ env.NEXT_VERSION }}
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${{ env.NEXT_VERSION }}


      # Create a release in GitHub
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.NEXT_VERSION }}
          release_name: ${{ env.NEXT_VERSION }}
          body: |
            ## What's Changed
            - Automated release by GitHub Actions
          draft: false
          prerelease: false

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GTH_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          TAG=${{ env.RELEASE_VERSION || 'latest' }}
          docker build -t ghcr.io/${{ github.repository_owner }}/k8s-monitoring-app:${TAG} .
          docker build -t ghcr.io/${{ github.repository_owner }}/k8s-monitoring-app:latest .

      # Push the Docker image
      - name: Push Docker image
        run: |
          TAG=${{ env.RELEASE_VERSION || 'latest' }}
          docker push ghcr.io/${{ github.repository_owner }}/k8s-monitoring-app:${TAG}
          docker push ghcr.io/${{ github.repository_owner }}/k8s-monitoring-app:latest

