name: Build and Push Docker Image

on:
  push:
    branches:
      - main

  release:
    types:
      - published
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Get the latest tag and bump the version
      # Generate next version
      - name: Generate next version
        id: version
        run: |
          # Get the latest tag and increment the patch version
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          IFS='.' read -r MAJOR MINOR PATCH <<< "${TAG#v}"
          PATCH=$((PATCH+2))
          NEXT_VERSION="v$MAJOR.$MINOR.$PATCH"

          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

      # Create a new Git tag
      - name: Create Git tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.NEXT_VERSION }}
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${{ env.NEXT_VERSION }}
          echo $NEXT_VERSION

      # Create GitHub release
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_VERSION: ${{ env.NEXT_VERSION }}
        run: |
          gh release create "$NEXT_VERSION" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${NEXT_VERSION#v}" \
              --generate-notes

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GTH_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          TAG=${{ env.RELEASE_VERSION || 'latest' }}
          docker build -t ghcr.io/${{ github.repository_owner }}/k8s-monitoring-app:${TAG} .
          docker build -t ghcr.io/${{ github.repository_owner }}/k8s-monitoring-app:latest .

      # Push the Docker image
      - name: Push Docker image
        run: |
          TAG=${{ env.RELEASE_VERSION || 'latest' }}
          docker push ghcr.io/${{ github.repository_owner }}/k8s-monitoring-app:${TAG}
          docker push ghcr.io/${{ github.repository_owner }}/k8s-monitoring-app:latest

